// Copies the shared "How to Write a Good Resume" guide (../shared/resume-guide.md)
// into a JS module the builder can import. Runs before `next dev` and `next build`.
// The server reads the same Markdown file to ground the AI chat, so edit the guide
// there, never the generated module.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const source = path.join(here, "../../shared/resume-guide.md");
const target = path.join(here, "../src/content/resumeGuide.js");

if (!fs.existsSync(source)) {
  // e.g. the client deployed on its own: keep the committed copy.
  console.log("sync-guide: shared/resume-guide.md not found, keeping", path.relative(process.cwd(), target));
  process.exit(0);
}

const markdown = fs.readFileSync(source, "utf8").trim();
const out = `// Generated by scripts/sync-guide.mjs from shared/resume-guide.md — do not edit by hand.\nexport const RESUME_GUIDE = ${JSON.stringify(markdown)};\n`;
if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== out) {
  fs.writeFileSync(target, out);
  console.log("sync-guide: updated", path.relative(process.cwd(), target));
}
