const CATEGORY_OF = require('../../shared/templates.json'); // generated by `npm run templates:export` in client/
const { PLAN_IDS } = require('./settings');
const { effectivePlanId } = require('./credits');

/** The plan id a template needs, from the admin's template settings (unknown ids need nothing). */
function templateTier(id, access) {
    const category = CATEGORY_OF[id];
    if (!category) return 'free';
    return access?.overrides?.[id] || access?.categories?.[category] || 'pro';
}

/** Whether this account may use a template right now (everything is open in free mode). */
function templateAllowed(user, settings, id) {
    if (settings.freeMode.enabled) return true;
    return PLAN_IDS.indexOf(templateTier(id, settings.templates)) <= Math.max(0, PLAN_IDS.indexOf(effectivePlanId(user)));
}

module.exports = { templateTier, templateAllowed };
